services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    expose:
      - "80"
      - "443"
    networks:
      - mailcow-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/certbot --email reyes875453@gmail.com --agree-tos --no-eff-email -d protocolocomercial.net -d protocolocomercial.net --expand  --non-interactive --agree-tos 
    networks:
      - mailcow-network
    depends_on:
      - nginx  

networks:
  mailcow-network:
    external: true
    name: mailcow-dockerized_mailcow-network